// src/renderer/src/components/video-player/controls/FullScreenButton.svelte
<script lang="ts">
  import * as Tooltip from "$ui/tooltip/";
  import { Button } from "$ui/button/";

  import Maximize from "~icons/lucide/maximize";
  import Minimize from "~icons/lucide/minimize";

  import { playerState } from "$lib/state/player.svelte";

  import { client } from "$/tipc";

  function toggleFullscreen() {
    if (playerState.isFullscreen) void client.exitFullscreen();
    else void client.enterFullscreen();

    playerState.isFullscreen = !playerState.isFullscreen;
  }
</script>

<Tooltip.Provider>
  <Tooltip.Root>
    <Tooltip.Trigger>
      <Button
        variant="ghost"
        size="icon"
        onclick={toggleFullscreen}
        class="h-8 w-8 rounded-full text-white transition-all duration-200 hover:bg-white/20 hover:text-blue-400 focus-visible:ring-blue-400"
        aria-label={playerState.isFullscreen ? "Exit fullscreen" : "Enter fullscreen"}
      >
        {#if playerState.isFullscreen}
          <Minimize class="size-4" />
        {:else}
          <Maximize class="size-4" />
        {/if}
      </Button>
    </Tooltip.Trigger>
    <Tooltip.Content>
      <p>Fullscreen</p>
    </Tooltip.Content>
  </Tooltip.Root>
</Tooltip.Provider>

// src/renderer/src/components/FullscreenButton.tsx
import { Maximize, Minimize } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip";
import { playbackCommands, usePlayerView } from "@/lib/store";

const controlItemClass = "h-full border-0 bg-transparent px-2.5 text-white hover:bg-white/10 rounded-none shadow-none transition-colors focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-white/20";

function FullscreenEnterButton() {
  const player = usePlayerView();
  return <Button
    className={controlItemClass}
    onClick={() => {
      void playbackCommands.setFullscreen(!player.isFullscreen);
    }}
    size="icon"
    type="button"
    variant="ghost"
  >
    {player.isFullscreen ? (
      <Minimize className="size-4" />
    ) : (
      <Maximize className="size-4" />
    )}
  </Button>
}

function FullscreenExitButton() {
  const player = usePlayerView();
  return <Button
    className={controlItemClass}
    onClick={() => {
      void playbackCommands.setFullscreen(!player.isFullscreen);
    }}
    size="icon"
    type="button"
    variant="ghost"
  >
    {player.isFullscreen ? (
      <Minimize className="size-4" />
    ) : (
      <Maximize className="size-4" />
    )}
  </Button>
}

export function FullscreenButton() {
  const player = usePlayerView();

  const button = player.isFullscreen ? <FullscreenExitButton /> : <FullscreenEnterButton />;

  return <Tooltip>
    <TooltipTrigger>
      {button}
    </TooltipTrigger>
    <TooltipContent>
      <p>{player.isFullscreen ? "Exit fullscreen" : "Enter fullscreen"}</p>
    </TooltipContent>
  </Tooltip>
}
