// src/renderer/src/components/settings/SettingsDialog.tsx
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogPanel, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Kbd } from "@/components/ui/kbd";
import type { ThemeMode } from "@/hooks/use-theme-mode";
import { formatHotkeyDisplay, hotkeyRecorder } from "@/lib/hotkey-recorder";
import { resetHotkeysToDefaults, updateHotkey } from "@/lib/hotkeys";
import { ChevronDownIcon, CloseIcon, MoonIcon, SettingsIcon, SunIcon } from "@/lib/icons";
import { useAppStore } from "@/lib/store";
import type { NotificationPosition } from "@/types";

const TABS = [
  { id: "general", label: "General" },
  { id: "playback", label: "Playback" },
  { id: "ui", label: "UI" },
  { id: "shortcuts", label: "Keyboard Shortcuts" }
] as const;

type SettingsTab = (typeof TABS)[number]["id"];

function tabButtonClass(active: boolean): string {
  return active
    ? "w-full justify-start text-left shadow-sm"
    : "w-full justify-start text-left text-muted-foreground";
}

export default function SettingsDialog({
  resolvedTheme,
  setTheme,
  theme
}: {
  resolvedTheme: "dark" | "light";
  setTheme: (theme: ThemeMode) => void;
  theme: ThemeMode;
}) {
  const state = useAppStore();
  const [selectedTab, setSelectedTab] = useState<SettingsTab>("general");
  const [editingAction, setEditingAction] = useState<string | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    if (state.settings.showDialog) {
      setSelectedTab("general");
    }
  }, [state.settings.showDialog]);

  if (!state.settings.showDialog) return null;

  const filteredCategories = state.hotkeys.categories
    .map((category) => ({
      ...category,
      actions: category.actions.filter((action) => {
        const display = formatHotkeyDisplay(action.keys);
        return (
          searchTerm.trim() === "" ||
          action.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
          display.toLowerCase().includes(searchTerm.toLowerCase())
        );
      })
    }))
    .filter((category) => category.actions.length > 0);

  return (
    <Dialog
      onOpenChange={(open) => useAppStore.getState().setSettingsDialogOpen(open)}
      open={state.settings.showDialog}
    >
      <DialogContent
        className="flex h-full w-full max-w-5xl flex-col overflow-hidden p-0 md:h-[85vh] md:flex-row"
        showCloseButton={false}
      >
        <Button
          className="absolute top-4 right-4 z-10 h-8 w-8 p-0"
          onClick={() => useAppStore.getState().setSettingsDialogOpen(false)}
          type="button"
          variant="ghost"
        >
          <CloseIcon className="h-4 w-4" />
        </Button>

        <aside className="border-sidebar-border bg-sidebar/60 w-full border-b p-4 md:w-64 md:border-r md:border-b-0">
          <h2 className="mb-4 px-3 text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
            Settings
          </h2>
          <nav
            className="space-y-1"
            onKeyDown={(event) => {
              const currentIndex = TABS.findIndex((tab) => tab.id === selectedTab);
              let nextIndex = currentIndex;
              if (event.key === "ArrowDown") {
                nextIndex = (currentIndex + 1) % TABS.length;
              } else if (event.key === "ArrowUp") {
                nextIndex = currentIndex === 0 ? TABS.length - 1 : currentIndex - 1;
              } else if (event.key === "Home") {
                nextIndex = 0;
              } else if (event.key === "End") {
                nextIndex = TABS.length - 1;
              } else {
                return;
              }
              event.preventDefault();
              setSelectedTab(TABS[nextIndex].id);
            }}
            role="tablist"
          >
            {TABS.map((tab) => (
              <Button
                aria-selected={selectedTab === tab.id}
                className={tabButtonClass(selectedTab === tab.id)}
                key={tab.id}
                onClick={() => setSelectedTab(tab.id)}
                role="tab"
                type="button"
                variant={selectedTab === tab.id ? "secondary" : "ghost"}
              >
                {tab.label}
              </Button>
            ))}
          </nav>
        </aside>

        <DialogPanel className="min-h-0 flex-1 overflow-y-auto p-6 md:p-8">
          <DialogTitle className="sr-only">Settings</DialogTitle>
          {selectedTab === "general" ? (
            <div className="space-y-6">
              <div>
                <h3 className="mb-3 text-base font-semibold">Application Theme</h3>
                <div className="flex flex-wrap gap-2">
                  <Button
                    className={tabButtonClass(theme === "light")}
                    onClick={() => setTheme("light")}
                    type="button"
                    variant={theme === "light" ? "secondary" : "outline"}
                  >
                    <span className="inline-flex items-center gap-2">
                      <SunIcon className="h-4 w-4" />
                      Light
                    </span>
                  </Button>
                  <Button
                    className={tabButtonClass(theme === "dark")}
                    onClick={() => setTheme("dark")}
                    type="button"
                    variant={theme === "dark" ? "secondary" : "outline"}
                  >
                    <span className="inline-flex items-center gap-2">
                      <MoonIcon className="h-4 w-4" />
                      Dark
                    </span>
                  </Button>
                  <Button
                    className={tabButtonClass(theme === "system")}
                    onClick={() => setTheme("system")}
                    type="button"
                    variant={theme === "system" ? "secondary" : "outline"}
                  >
                    <span className="inline-flex items-center gap-2">
                      <SettingsIcon className="h-4 w-4" />
                      System ({resolvedTheme})
                    </span>
                  </Button>
                </div>
              </div>
            </div>
          ) : null}

          {selectedTab === "playback" ? (
            <div className="space-y-6">
              <div>
                <h3 className="mb-2 text-base font-semibold">Playback</h3>
                <p className="mb-3 text-sm text-muted-foreground">
                  Autoplay follows queue selection and starts on load when a file or folder is opened.
                </p>
              </div>

              <div>
                <label className="mb-2 block text-sm font-medium">Current Volume</label>
                <input
                  className="w-full accent-primary"
                  max={1}
                  min={0}
                  onChange={(event) => {
                    const next = Number(event.target.value);
                    useAppStore.getState().setVolume(next);
                    if (next > 0) {
                      useAppStore.getState().setMuted(false);
                    }
                  }}
                  step={0.01}
                  type="range"
                  value={state.volume.value}
                />
              </div>
            </div>
          ) : null}

          {selectedTab === "ui" ? (
            <div className="space-y-6">
              <div>
                <h3 className="mb-3 text-base font-semibold">Video Notifications</h3>
                <label className="flex items-center gap-3 text-sm">
                  <Checkbox
                    checked={state.notifications.upNextEnabled}
                    onCheckedChange={(checked) =>
                      useAppStore
                        .getState()
                        .setNotificationSettings({ upNextEnabled: checked === true })
                    }
                  />
                  Show "Up Next" notification
                </label>
              </div>

              <div>
                <label className="flex items-center gap-3 text-sm">
                  <Checkbox
                    checked={state.notifications.videoInfoEnabled}
                    onCheckedChange={(checked) =>
                      useAppStore
                        .getState()
                        .setNotificationSettings({ videoInfoEnabled: checked === true })
                    }
                  />
                  Show video info overlay
                </label>
              </div>

              <div>
                <label className="mb-2 block text-sm font-medium">Up Next Position</label>
                <div className="relative max-w-xs">
                  <select
                    className="h-10 w-full appearance-none rounded-md border border-input bg-background px-3 pr-10 text-sm"
                    onChange={(event) =>
                      useAppStore.getState().setNotificationSettings({
                        upNextPosition: event.target.value as NotificationPosition
                      })
                    }
                    value={state.notifications.upNextPosition}
                  >
                    <option value="top-left">Top Left</option>
                    <option value="top-right">Top Right</option>
                    <option value="bottom-left">Bottom Left</option>
                    <option value="bottom-right">Bottom Right</option>
                  </select>
                  <ChevronDownIcon className="pointer-events-none absolute top-1/2 right-3 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                </div>
              </div>
            </div>
          ) : null}

          {selectedTab === "shortcuts" ? (
            <div className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <h3 className="text-base font-semibold">Keyboard Shortcuts</h3>
                <Button
                  onClick={() => resetHotkeysToDefaults()}
                  type="button"
                  variant="outline"
                >
                  Reset to Defaults
                </Button>
              </div>

              <Input
                onChange={(event) => setSearchTerm(event.target.value)}
                placeholder="Search shortcuts..."
                type="text"
                value={searchTerm}
              />

              {state.hotkeys.categories.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  Shortcut bindings will appear here once the hotkey layer is wired.
                </p>
              ) : (
                filteredCategories.map((category) => (
                  <div className="rounded-lg border" key={category.name}>
                    <div className="border-b px-4 py-3 text-sm font-semibold">{category.name}</div>
                    <div>
                      {category.actions.map((action) => (
                        <div
                          className="flex items-center justify-between gap-4 border-b px-4 py-3 last:border-b-0"
                          key={action.id}
                        >
                          <div className="text-sm text-muted-foreground">{action.description}</div>
                          <div className="flex items-center gap-2">
                            <Kbd className="h-7 text-xs">
                              {isRecording && editingAction === action.id
                                ? "Press hotkey..."
                                : action.keys.length > 0
                                  ? formatHotkeyDisplay(action.keys)
                                  : "None"}
                            </Kbd>
                            {isRecording && editingAction === action.id ? (
                              <Button
                                className="h-8 w-8 p-0"
                                onClick={() => {
                                  hotkeyRecorder.cancelRecording();
                                  setEditingAction(null);
                                  setIsRecording(false);
                                }}
                                size="sm"
                                type="button"
                                variant="outline"
                              >
                                <CloseIcon className="h-4 w-4" />
                              </Button>
                            ) : (
                              <Button
                                disabled={action.configurable === false}
                                onClick={() => {
                                  if (editingAction) {
                                    hotkeyRecorder.cancelRecording();
                                  }

                                  setEditingAction(action.id);
                                  setIsRecording(true);
                                  hotkeyRecorder.startRecording(
                                    (result) => {
                                      updateHotkey(action.id, result.keys);
                                      setEditingAction(null);
                                      setIsRecording(false);
                                    },
                                    () => {
                                      setEditingAction(null);
                                      setIsRecording(false);
                                    }
                                  );
                                }}
                                size="sm"
                                type="button"
                                variant="outline"
                              >
                                Edit
                              </Button>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))
              )}
            </div>
          ) : null}
        </DialogPanel>
      </DialogContent>
    </Dialog>
  );
}

// src/renderer/src/components/settings-dialog.svelte
<script lang="ts">
  import * as Dialog from "@/components/ui/dialog";
  import HotkeySettings from "./hotkey-settings.svelte";
  import IconSettings from "lucide-svelte/icons/settings";
  import IconKeyboard from "lucide-svelte/icons/keyboard";
  import IconPlayerPlay from "lucide-svelte/icons/play";
  import IconVolume2 from "lucide-svelte/icons/volume-2";
  import SunIcon from "lucide-svelte/icons/sun";
  import MoonIcon from "lucide-svelte/icons/moon";
  import MonitorIcon from "lucide-svelte/icons/monitor";
  import ChevronDownIcon from "lucide-svelte/icons/chevron-down";

  import { resetMode, setMode, mode } from "mode-watcher";
  import * as DropdownMenu from "@/components/ui/dropdown-menu/";
  import { Label } from "@/components/ui/label";

  let { open: isOpen = $bindable() }: { open: boolean } = $props();

  const SettingsCategory = {
    General: "general",
    Playback: "playback",
    Audio: "audio",
    Shortcuts: "shortcuts"
  } as const;

  const categoryItems = [
    {
      id: SettingsCategory.General,
      label: "General",
      icon: IconSettings
    },
    {
      id: SettingsCategory.Playback,
      label: "Playback",
      icon: IconPlayerPlay
    },
    {
      id: SettingsCategory.Audio,
      label: "Audio",
      icon: IconVolume2
    },
    {
      id: SettingsCategory.Shortcuts,
      label: "Keyboard Shortcuts",
      icon: IconKeyboard
    }
  ];

  let selectedCategory: string = $state(SettingsCategory.General);
</script>

<Dialog.Root bind:open={isOpen}>
  <Dialog.Content
    class="flex h-[85vh] w-[90vw] max-w-6xl flex-col overflow-hidden p-0 sm:max-w-none"
    showCloseButton={true}
  >
    <div class="flex flex-1 overflow-hidden">
      <!-- Sidebar -->
      <aside class="border-sidebar-border bg-sidebar w-72 flex-shrink-0 border-r">
        <div class="flex h-full flex-col">
          <div class="p-4">
            <nav class="space-y-1">
              {#each categoryItems as category (category.id)}
                {@const IconComponent = category.icon}
                <button
                  class="group flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-all duration-200 {selectedCategory ===
                  category.id
                    ? 'bg-sidebar-primary text-sidebar-primary-foreground shadow-lg'
                    : 'text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground'}"
                  onclick={() => (selectedCategory = category.id)}
                >
                  <IconComponent
                    size={18}
                    class={selectedCategory === category.id
                      ? "text-sidebar-primary-foreground"
                      : "text-sidebar-foreground/70 group-hover:text-sidebar-accent-foreground"}
                  />
                  <div class="text-sm font-medium">{category.label}</div>
                </button>
              {/each}
            </nav>
          </div>
        </div>
      </aside>

      <!-- Main Content -->
      <main class="flex-1 overflow-y-auto">
        <div class="p-6">
          <div class="space-y-6">
            {#if selectedCategory === SettingsCategory.General}
              <div class="space-y-6">
                <div class="flex flex-col space-y-3">
                  <Label class="text-foreground text-base font-medium">Application Theme</Label>
                  <DropdownMenu.Root>
                    <DropdownMenu.Trigger
                      class="bg-card border-border text-card-foreground hover:bg-accent hover:border-accent-foreground focus:ring-ring focus:ring-offset-background inline-flex w-fit items-center justify-between gap-3 rounded-lg border px-4 py-3 text-sm font-medium transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none"
                    >
                      <div class="flex items-center gap-2">
                        {#if mode.current === "light"}
                          <SunIcon class="h-4 w-4 text-yellow-500" />
                          <span>Light</span>
                        {:else if mode.current === "dark"}
                          <MoonIcon class="h-4 w-4 text-blue-400" />
                          <span>Dark</span>
                        {:else}
                          <MonitorIcon class="text-muted-foreground h-4 w-4" />
                          <span>System</span>
                        {/if}
                      </div>
                      <ChevronDownIcon class="text-muted-foreground h-4 w-4" />
                    </DropdownMenu.Trigger>
                    <DropdownMenu.Content align="start" class="w-48">
                      <DropdownMenu.Item
                        onclick={() => setMode("light")}
                        class="flex items-center gap-2 {mode.current === 'light'
                          ? 'bg-blue-600 text-white'
                          : ''}"
                      >
                        <SunIcon class="h-4 w-4 text-yellow-500" />
                        Light
                        {#if mode.current === "light"}
                          <div class="ml-auto h-2 w-2 rounded-full bg-white"></div>
                        {/if}
                      </DropdownMenu.Item>
                      <DropdownMenu.Item
                        onclick={() => setMode("dark")}
                        class="flex items-center gap-2 {mode.current === 'dark'
                          ? 'bg-blue-600 text-white'
                          : ''}"
                      >
                        <MoonIcon class="h-4 w-4 text-blue-400" />
                        Dark
                        {#if mode.current === "dark"}
                          <div class="ml-auto h-2 w-2 rounded-full bg-white"></div>
                        {/if}
                      </DropdownMenu.Item>
                      <DropdownMenu.Item
                        onclick={() => resetMode()}
                        class="flex items-center gap-2 {mode.current !== 'light' &&
                        mode.current !== 'dark'
                          ? 'bg-blue-600 text-white'
                          : ''}"
                      >
                        <MonitorIcon class="text-muted-foreground h-4 w-4" />
                        System
                        {#if mode.current !== "light" && mode.current !== "dark"}
                          <div class="ml-auto h-2 w-2 rounded-full bg-white"></div>
                        {/if}
                      </DropdownMenu.Item>
                    </DropdownMenu.Content>
                  </DropdownMenu.Root>
                </div>
              </div>
            {:else if selectedCategory === SettingsCategory.Playback}
              <div class="space-y-4">
                <div class="bg-card rounded-lg p-4">
                  <h3 class="text-card-foreground mb-2 text-lg font-medium">Playback Options</h3>
                  <p class="text-muted-foreground mb-3 text-sm">
                    Configure video and media playback
                  </p>
                  <div class="text-muted-foreground text-sm">
                    Playback settings will be implemented here.
                  </div>
                </div>
              </div>
            {:else if selectedCategory === SettingsCategory.Audio}
              <div class="space-y-4">
                <div class="bg-card rounded-lg p-4">
                  <h3 class="text-card-foreground mb-2 text-lg font-medium">Audio Settings</h3>
                  <p class="text-muted-foreground mb-3 text-sm">
                    Audio output and processing options
                  </p>
                  <div class="text-muted-foreground text-sm">
                    Audio settings will be implemented here.
                  </div>
                </div>
              </div>
            {:else if selectedCategory === SettingsCategory.Shortcuts}
              <div class="space-y-4">
                <div class="bg-card rounded-lg p-4">
                  <h3 class="text-card-foreground mb-2 text-lg font-medium">Keyboard Shortcuts</h3>
                  <p class="text-muted-foreground mb-3 text-sm">
                    Customize hotkeys and key bindings
                  </p>
                  <HotkeySettings />
                </div>
              </div>
            {/if}
          </div>
        </div>
      </main>
    </div>
  </Dialog.Content>
</Dialog.Root>
