// src/renderer/src/components/sidebar.svelte
<script lang="ts">
  /* eslint-disable import-x/no-duplicates */
  import { cubicOut } from "svelte/easing";
  import { fly } from "svelte/transition";
  /* eslint-enable import-x/no-duplicates */
  import { SidebarTab } from "$/types";
  import * as Tabs from "$ui/tabs/";
  import TabFileBrowser from "./sidebar/tab-file-browser.svelte";
  import TabQueue from "./sidebar/tab-playlist-queue.svelte";
  import { sidebarState } from "$lib/state/sidebar.svelte";
</script>

<div class="border-sidebar-border bg-sidebar flex h-full flex-col border-r p-4 backdrop-blur-xl">
  <Tabs.Root
    value={sidebarState.currentTab}
    class="flex h-full w-full flex-col"
    onValueChange={(value) => (sidebarState.currentTab = value as SidebarTab)}
  >
    <Tabs.List
      class="border-sidebar-border bg-sidebar-accent grid w-full grid-cols-2 gap-1 rounded-lg border p-0"
    >
      <Tabs.Trigger value={SidebarTab.FileBrowser} class="text-sidebar-foreground h-full flex-1"
        >Files</Tabs.Trigger
      >
      <Tabs.Trigger value={SidebarTab.Queue} class="text-sidebar-foreground h-full flex-1"
        >Queue</Tabs.Trigger
      >
    </Tabs.List>

    <div class="relative flex-1 overflow-hidden">
      {#key sidebarState.currentTab}
        <div
          class="absolute inset-0 flex h-full w-full"
          in:fly={{
            x: sidebarState.currentTab === SidebarTab.FileBrowser ? -300 : 300,
            duration: 300,
            easing: cubicOut
          }}
          out:fly={{
            x: sidebarState.currentTab === SidebarTab.FileBrowser ? 300 : -300,
            duration: 300,
            easing: cubicOut
          }}
        >
          {#if sidebarState.currentTab === SidebarTab.FileBrowser}
            <div class="h-full w-full overflow-hidden">
              <TabFileBrowser />
            </div>
          {:else if sidebarState.currentTab === SidebarTab.Queue}
            <div class="h-full w-full overflow-hidden">
              <TabQueue />
            </div>
          {/if}
        </div>
      {/key}
    </div>
  </Tabs.Root>
</div>

// src/renderer/src/components/Sidebar.tsx
import { Settings } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { QueuePanel } from "./queue/QueuePanel";
import { FileBrowserPanel } from "./file-browser/FileBrowserPanel";
import { useSettingsStore } from "@/stores/settings";
import { useSidebarStore } from "@/stores/sidebar";
import { cn } from "@/lib/utils";
import type { SidebarTab } from "@/types";

export function Sidebar() {
  const currentTab = useSidebarStore((state) => state.currentTab);
  const position = useSidebarStore((state) => state.position);
  const setSidebarTab = useSidebarStore((state) => state.setSidebarTab);
  const setSidebarDragging = useSidebarStore((state) => state.setSidebarDragging);
  const setSettingsDialogOpen = useSettingsStore((state) => state.setSettingsDialogOpen);

  const isLeft = position === "left";

  return (
    <Tabs
      className="group/sidebar relative flex h-full flex-col overflow-hidden"
      onValueChange={(value) => setSidebarTab(value as SidebarTab)}
      value={currentTab}
    >
      <div
        className={cn(
          "absolute top-1/2 z-50 h-16 w-0.5 -translate-y-1/2 rounded-full",
          "bg-primary/20 opacity-0 transition-all duration-500",
          "group-hover/sidebar:opacity-100 group-active/sidebar:h-24 group-active/sidebar:bg-primary/40",
          isLeft ? "-right-px" : "-left-px"
        )}
      />

      <div className="px-4 pt-4 pb-1">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="file-browser">Files</TabsTrigger>
          <TabsTrigger value="queue">Queue</TabsTrigger>
        </TabsList>
      </div>

      <div className="min-h-0 flex-1 overflow-hidden px-4 pt-0">
        <TabsContent className="flex min-h-0 flex-1 flex-col" value="file-browser">
          <FileBrowserPanel />
        </TabsContent>
        <TabsContent className="flex min-h-0 flex-1 flex-col" value="queue">
          <QueuePanel />
        </TabsContent>
      </div>

      <div className="px-4 pt-2 pb-4">
        <div className="grid grid-cols-3 items-center">
          <div className="flex items-center justify-start">
            {isLeft && (
              <Button
                className="h-7 px-2 text-xs"
                onClick={() => setSettingsDialogOpen(true)}
                size="icon"
                variant="ghost"
              >
                <Settings className="size-4" />
              </Button>
            )}
          </div>

          <div
            className="group flex cursor-grab items-center justify-center py-2 active:cursor-grabbing"
            onMouseDown={(e) => {
              e.preventDefault();
              setSidebarDragging(true);
            }}
          >
            <div className="bg-border h-1 w-16 rounded-full opacity-60 transition-all group-hover:w-24 group-hover:opacity-100" />
          </div>

          <div className="flex items-center justify-end">
            {!isLeft && (
              <Button
                className="h-7 px-2 text-xs"
                onClick={() => setSettingsDialogOpen(true)}
                size="icon"
                variant="ghost"
              >
                <Settings className="size-4" />
              </Button>
            )}
          </div>
        </div>
      </div>
    </Tabs>
  );
}
