// src/renderer/src/components/VideoPlayer.tsx
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import {
  CloseIcon,
  FilmIcon,
  FullscreenIcon,
  LoaderIcon,
  MuteIcon,
  NextIcon,
  PanelLeftIcon,
  PauseIcon,
  PlayIcon,
  PreviousIcon,
  SettingsIcon,
  VolumeIcon
} from "@/lib/icons";
import { makeTimeString } from "@/lib/make-time-string";
import { getCurrentQueueItem, toFileUrl, useAppStore } from "@/lib/store";

type HoldDirection = "left" | "right" | null;

function controlButtonClass(): string {
  return "h-9 border-white/10 bg-white/10 px-3 text-sm text-white hover:bg-white/15";
}

function iconControlButtonClass(): string {
  return "size-9 border-white/10 bg-white/10 p-0 text-white hover:bg-white/15";
}

function UpNextNotification() {
  const state = useAppStore();
  const [isDismissed, setIsDismissed] = useState(false);

  const remaining = state.player.duration - state.player.currentTime;
  const showNotification =
    state.notifications.upNextEnabled &&
    !isDismissed &&
    state.player.duration > 0 &&
    remaining <= 10 &&
    remaining > 0 &&
    (state.queue.index < state.queue.items.length - 1 || state.queue.repeatMode === "all");

  useEffect(() => {
    setIsDismissed(false);
  }, [state.player.currentVideo]);

  if (!showNotification) return null;

  const nextItem =
    state.queue.index < state.queue.items.length - 1
      ? state.queue.items[state.queue.index + 1]
      : state.queue.items[0];

  const positionClass = {
    "bottom-left": "bottom-24 left-8",
    "bottom-right": "bottom-24 right-8",
    "top-left": "top-8 left-8",
    "top-right": "top-8 right-8"
  }[state.notifications.upNextPosition];

  return (
    <div
      className={`absolute z-40 flex max-w-sm flex-col gap-3 rounded-xl border border-border/60 bg-card/95 p-4 shadow-xl backdrop-blur-md ${positionClass}`}
    >
      <div className="flex items-center justify-between gap-2">
        <span className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
          Up Next
        </span>
        <Button
          className="size-8 p-0 text-muted-foreground hover:text-foreground"
          onClick={() => setIsDismissed(true)}
          size="icon-sm"
          type="button"
          variant="ghost"
        >
          <CloseIcon className="h-4 w-4" />
        </Button>
      </div>

      <div className="line-clamp-2 text-base font-semibold">{nextItem?.name}</div>
      <div className="h-1 overflow-hidden rounded-full bg-muted/50">
        <div
          className="h-full rounded-full bg-primary/70 transition-all"
          style={{ width: `${Math.max(0, Math.min(100, (remaining / 10) * 100))}%` }}
        />
      </div>
      <div className="text-xs text-muted-foreground">Playing in {Math.ceil(remaining)}s</div>
    </div>
  );
}

function VideoInfoOverlay({ visible }: { visible: boolean }) {
  const state = useAppStore();
  const currentItem = getCurrentQueueItem(state);

  if (!visible || !currentItem || !state.notifications.videoInfoEnabled) return null;

  return (
    <div className="pointer-events-none absolute top-0 left-0 z-20 w-full bg-gradient-to-b from-black/70 via-black/40 to-transparent p-8 pb-16">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold text-white drop-shadow-[0_2px_8px_rgba(0,0,0,0.8)]">
          {currentItem.name}
        </h1>
        {state.queue.items.length > 1 ? (
          <p className="text-sm font-medium text-white/75">
            Video {state.queue.index + 1} of {state.queue.items.length}
          </p>
        ) : null}
      </div>
    </div>
  );
}

function PlayerControls({
  onControlsMouseEnter,
  onControlsMouseLeave
}: {
  onControlsMouseEnter: () => void;
  onControlsMouseLeave: () => void;
}) {
  const state = useAppStore();
  const [dragTime, setDragTime] = useState<number | null>(null);
  const [hoverTime, setHoverTime] = useState(0);
  const [isDragging, setIsDragging] = useState(false);

  const progressTime = dragTime ?? state.player.currentTime;
  const progressPercentage =
    state.player.duration > 0 ? (progressTime / state.player.duration) * 100 : 0;

  function seekTo(clientX: number, rect: DOMRect): number {
    const percent = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    return percent * state.player.duration;
  }

  function setVideoTime(nextTime: number): void {
    useAppStore.getState().setCurrentTime(nextTime);
    const video = document.querySelector("video");
    if (video) {
      video.currentTime = nextTime;
    }
  }

  function handleProgressMouseDown(event: import("react").MouseEvent<HTMLDivElement>): void {
    if (!state.player.duration) return;
    event.preventDefault();
    const rect = event.currentTarget.getBoundingClientRect();
    const wasPlaying = state.player.isPlaying;

    setIsDragging(true);
    setDragTime(seekTo(event.clientX, rect));

    if (wasPlaying) {
      useAppStore.getState().pausePlayback();
    }

    const handleMouseMove = (moveEvent: MouseEvent) => {
      setDragTime(seekTo(moveEvent.clientX, rect));
    };

    const handleMouseUp = async (upEvent: MouseEvent) => {
      const nextTime = seekTo(upEvent.clientX, rect);
      setVideoTime(nextTime);
      setDragTime(null);
      setIsDragging(false);
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
      if (wasPlaying) {
        await useAppStore.getState().togglePlayPause();
      }
    };

    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);
  }

  return (
    <div
      className="absolute inset-x-0 bottom-0 z-30 bg-gradient-to-t from-black/90 via-black/60 to-transparent px-6 pb-4 pt-20"
      id="media-controls"
      onMouseEnter={onControlsMouseEnter}
      onMouseLeave={onControlsMouseLeave}
    >
      <div className="mb-3 flex items-center justify-between text-sm font-mono text-white/90">
        <span>{makeTimeString(progressTime)}</span>
        <span>{state.player.duration ? makeTimeString(state.player.duration) : "0:00"}</span>
      </div>

      <div className="relative mb-4">
        <div
          className="relative h-2 cursor-pointer rounded-full bg-white/20"
          onClick={(event) => {
            if (isDragging || !state.player.duration) return;
            const rect = event.currentTarget.getBoundingClientRect();
            setVideoTime(seekTo(event.clientX, rect));
          }}
          onMouseDown={handleProgressMouseDown}
          onMouseMove={(event) => {
            if (!state.player.duration || isDragging) return;
            const rect = event.currentTarget.getBoundingClientRect();
            setHoverTime(seekTo(event.clientX, rect));
          }}
          role="slider"
          tabIndex={0}
        >
          <div
            className="absolute top-0 left-0 h-full rounded-full bg-primary transition-all"
            style={{ width: `${progressPercentage}%` }}
          />
          <div
            className="absolute top-1/2 h-4 w-4 -translate-y-1/2 rounded-full border-2 border-white bg-primary shadow"
            style={{ left: `calc(${progressPercentage}% - 8px)` }}
          />
        </div>

        {!isDragging && state.player.duration > 0 ? (
          <div
            className="pointer-events-none absolute -top-8 rounded bg-black/70 px-2 py-1 text-xs text-white"
            style={{
              left: `${Math.max(0, Math.min(95, (hoverTime / state.player.duration) * 100))}%`
            }}
          >
            {makeTimeString(hoverTime)}
          </div>
        ) : null}
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Button
            className={iconControlButtonClass()}
            onClick={() => useAppStore.getState().toggleSidebar()}
            size="icon"
            type="button"
            variant="outline"
          >
            <PanelLeftIcon className="h-4 w-4" />
          </Button>
          <Button
            className={iconControlButtonClass()}
            onClick={() => {
              void useAppStore.getState().playPreviousVideo();
            }}
            size="icon"
            type="button"
            variant="outline"
          >
            <PreviousIcon className="h-4 w-4" />
          </Button>
          <Button
            className={iconControlButtonClass()}
            onClick={() => {
              void useAppStore.getState().togglePlayPause();
            }}
            size="icon"
            type="button"
            variant="outline"
          >
            {state.player.isPlaying ? (
              <PauseIcon className="h-4 w-4" />
            ) : (
              <PlayIcon className="h-4 w-4" />
            )}
          </Button>
          <Button
            className={iconControlButtonClass()}
            onClick={() => {
              void useAppStore.getState().playNextVideo();
            }}
            size="icon"
            type="button"
            variant="outline"
          >
            <NextIcon className="h-4 w-4" />
          </Button>
        </div>

        <div className="flex items-center gap-2">
          <Button
            className={iconControlButtonClass()}
            onClick={() => useAppStore.getState().setMuted(!state.volume.isMuted)}
            size="icon"
            type="button"
            variant="outline"
          >
            {state.volume.isMuted || state.volume.value === 0 ? (
              <MuteIcon className="h-4 w-4" />
            ) : (
              <VolumeIcon className="h-4 w-4" />
            )}
          </Button>
          <input
            className="accent-primary"
            max={1}
            min={0}
            onChange={(event) => {
              useAppStore.getState().setVolume(Number(event.target.value));
              if (Number(event.target.value) > 0) {
                useAppStore.getState().setMuted(false);
              }
            }}
            step={0.01}
            type="range"
            value={state.volume.value}
          />
          <select
            className={controlButtonClass()}
            onChange={(event) => {
              useAppStore.getState().setPlayerState({
                aspectRatio: event.target.value as "contain" | "cover" | "fill"
              });
            }}
            value={state.player.aspectRatio}
          >
            <option value="contain">Contain</option>
            <option value="cover">Cover</option>
            <option value="fill">Fill</option>
          </select>
          <Button
            className={iconControlButtonClass()}
            onClick={() => useAppStore.getState().setSettingsDialogOpen(true)}
            size="icon"
            type="button"
            variant="outline"
          >
            <SettingsIcon className="h-4 w-4" />
          </Button>
          <Button
            className={iconControlButtonClass()}
            onClick={() => {
              void useAppStore.getState().setFullscreen(!state.player.isFullscreen);
            }}
            size="icon"
            type="button"
            variant="outline"
          >
            <FullscreenIcon className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}

export default function VideoPlayer() {
  const state = useAppStore();
  const currentItem = getCurrentQueueItem(state);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const hideTimerRef = useRef<number | null>(null);
  const holdTimerRef = useRef<number | null>(null);
  const holdIntervalRef = useRef<number | null>(null);
  const [showControls, setShowControls] = useState(true);
  const [isControlsHovered, setIsControlsHovered] = useState(false);
  const [holdDirection, setHoldDirection] = useState<HoldDirection>(null);

  useEffect(() => {
    useAppStore.getState().bindVideoElement(videoRef.current);
    return () => {
      useAppStore.getState().bindVideoElement(null);
    };
  }, []);

  useEffect(() => {
    useAppStore.getState().setPlayerState({ showControls });
  }, [showControls]);

  useEffect(() => {
    if (!state.player.isPlaying) {
      setShowControls(true);
      if (hideTimerRef.current) {
        window.clearTimeout(hideTimerRef.current);
      }
      return;
    }

    resetHideTimer();
    return () => {
      if (hideTimerRef.current) {
        window.clearTimeout(hideTimerRef.current);
      }
    };
  }, [state.player.isPlaying, currentItem?.id]);

  function resetHideTimer(): void {
    if (hideTimerRef.current) {
      window.clearTimeout(hideTimerRef.current);
    }

    setShowControls(true);

    if (!isControlsHovered && state.player.isPlaying) {
      hideTimerRef.current = window.setTimeout(() => {
        if (!isControlsHovered) {
          setShowControls(false);
        }
      }, 3000);
    }
  }

  function stopHoldSeeking(): void {
    setHoldDirection(null);
    useAppStore.getState().setPlayerState({ isHolding: false });
    if (holdTimerRef.current) {
      window.clearTimeout(holdTimerRef.current);
      holdTimerRef.current = null;
    }
    if (holdIntervalRef.current) {
      window.clearInterval(holdIntervalRef.current);
      holdIntervalRef.current = null;
    }
  }

  useEffect(() => {
    return () => {
      stopHoldSeeking();
    };
  }, []);

  function startHoldSeeking(direction: HoldDirection): void {
    if (!videoRef.current || !direction) return;
    useAppStore.getState().setPlayerState({ isHolding: true });
    setHoldDirection(direction);

    holdIntervalRef.current = window.setInterval(() => {
      if (!videoRef.current) {
        stopHoldSeeking();
        return;
      }

      const seekAmount = 0.3;
      const nextTime =
        direction === "right"
          ? Math.min(videoRef.current.currentTime + seekAmount, state.player.duration)
          : Math.max(videoRef.current.currentTime - seekAmount, 0);

      videoRef.current.currentTime = nextTime;
      useAppStore.getState().setCurrentTime(nextTime);
    }, 100);
  }

  if (!currentItem) {
    return (
      <div
        className="group flex h-full w-full items-center justify-center bg-black/90 text-center text-muted-foreground transition hover:bg-black/80"
        onDoubleClick={() => {
          void useAppStore.getState().loadFileSystemStructure();
        }}
      >
        <div>
          <FilmIcon className="mx-auto mb-4 h-12 w-12 opacity-50" />
          <p className="text-base font-medium">No video selected</p>
          <p className="text-sm opacity-70">Double-click to open a file or folder</p>
        </div>
      </div>
    );
  }

  return (
    <div className="relative flex h-full w-full flex-col" id="video-player">
      <div
        className={`relative flex min-h-0 flex-1 items-center justify-center bg-black ${
          showControls ? "" : "cursor-none"
        }`}
        id="video-container"
        onDoubleClick={async (event) => {
          const target = event.target as HTMLElement | null;
          if (target?.closest("#media-controls")) return;
          await useAppStore.getState().togglePlayPause();
        }}
        onMouseDown={(event) => {
          if (event.button !== 0 || !videoRef.current) return;
          const target = event.target as HTMLElement | null;
          if (target?.closest("#media-controls")) return;
          const rect = containerRef.current?.getBoundingClientRect();
          if (!rect) return;

          const direction: HoldDirection =
            event.clientX - rect.left < rect.width / 2 ? "left" : "right";
          holdTimerRef.current = window.setTimeout(() => {
            startHoldSeeking(direction);
          }, 300);

          const cleanup = () => {
            stopHoldSeeking();
            window.removeEventListener("mouseup", cleanup);
          };
          window.addEventListener("mouseup", cleanup, { once: true });
        }}
        onMouseLeave={() => {
          if (hideTimerRef.current) {
            window.clearTimeout(hideTimerRef.current);
          }
          if (state.player.isPlaying && !isControlsHovered) {
            setShowControls(false);
          }
        }}
        onMouseMove={() => resetHideTimer()}
        ref={containerRef}
      >
        <video
          className={`h-full w-full bg-black ${
            state.player.aspectRatio === "cover"
              ? "object-cover"
              : state.player.aspectRatio === "fill"
                ? "object-fill"
                : "object-contain"
          }`}
          controls={false}
          disablePictureInPicture
          onCanPlay={() => useAppStore.getState().setPlayerState({ isLoading: false })}
          onEnded={() => {
            if (state.queue.repeatMode === "one" && videoRef.current) {
              videoRef.current.currentTime = 0;
              useAppStore.getState().setCurrentTime(0);
              void videoRef.current.play();
              return;
            }
            void useAppStore.getState().playNextVideo();
          }}
          onError={() => {
            useAppStore.getState().setPlayerState({
              error: "Video format not supported or file could not be played.",
              isLoading: false
            });
          }}
          onLoadedData={() => {
            useAppStore.getState().setPlayerState({ isLoading: false });
            if (videoRef.current) {
              useAppStore.getState().setDuration(videoRef.current.duration);
              void videoRef.current.play().catch(() => undefined);
            }
          }}
          onLoadedMetadata={() => {
            if (videoRef.current) {
              useAppStore.getState().setDuration(videoRef.current.duration);
            }
          }}
          onLoadStart={() => useAppStore.getState().setPlayerState({ isLoading: true })}
          onPause={() => useAppStore.getState().setPlayerState({ isPlaying: false })}
          onPlay={() => useAppStore.getState().setPlayerState({ isPlaying: true })}
          onSeeked={() => {
            if (videoRef.current) {
              useAppStore.getState().setCurrentTime(videoRef.current.currentTime);
            }
          }}
          onTimeUpdate={() => {
            if (videoRef.current) {
              useAppStore.getState().setCurrentTime(videoRef.current.currentTime);
            }
          }}
          preload="metadata"
          ref={videoRef}
          src={toFileUrl(currentItem.path)}
        />

        {state.player.isLoading ? (
          <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/40">
            <LoaderIcon className="h-8 w-8 animate-spin text-white" />
          </div>
        ) : null}

        {state.player.error ? (
          <div className="absolute top-6 left-1/2 z-30 -translate-x-1/2 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-2 text-sm text-destructive">
            {state.player.error}
          </div>
        ) : null}

        {holdDirection ? (
          <div
            className={`pointer-events-none absolute top-1/2 z-20 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-black/40 text-white backdrop-blur-sm ${
              holdDirection === "left" ? "left-8" : "right-8"
            }`}
          >
            {holdDirection === "left" ? "←" : "→"}
          </div>
        ) : null}

        <VideoInfoOverlay visible={showControls} />
        <UpNextNotification />
        <PlayerControls
          onControlsMouseEnter={() => {
            setIsControlsHovered(true);
            setShowControls(true);
          }}
          onControlsMouseLeave={() => {
            setIsControlsHovered(false);
            resetHideTimer();
          }}
        />
      </div>
    </div>
  );
}

// src/renderer/src/components/video-player/video-player.svelte
<script lang="ts">
  import { fileBrowserState } from "$lib/state/file-browser.svelte";
  import { playerState } from "$lib/state/player.svelte";
  import { queue } from "$lib/state/queue.svelte";
  import { cn } from "$lib/utils";
  import VideoPlayerControls from "./video-player-controls.svelte";
  import UpNextNotification from "./notifications/UpNextNotification.svelte";
  import VideoInfoDisplay from "./notifications/VideoInfoDisplay.svelte";

  type AspectRatioMode = "contain" | "cover" | "fill";
  let aspectRatio: AspectRatioMode = $state("contain");
  let videoAspectRatio = $state<number | null>(null);

  let restoring = playerState.currentVideo !== null;
  let resumeTime = playerState.currentTime;
  let resumePlaying = playerState.isPlaying;

  const aspectRatioClass = $derived(() => {
    switch (aspectRatio) {
      case "contain":
        return "object-contain";
      case "cover":
        return "object-cover";
      case "fill":
        return "object-fill";
      default:
        return "";
    }
  });

  // Floating controls state
  let showControls = $state(true);
  let hideTimeout: ReturnType<typeof setTimeout> | null = null;
  let isControlsHovered = $state(false);

  // Auto-hide controls after inactivity
  function resetHideTimer(): void {
    if (hideTimeout) {
      clearTimeout(hideTimeout);
    }

    showControls = true;

    // Don't hide controls if they're being hovered or if video is paused
    if (!isControlsHovered && playerState.isPlaying) {
      hideTimeout = setTimeout(() => {
        if (!isControlsHovered) {
          showControls = false;
        }
      }, 3000); // Hide after 3 seconds of inactivity
    }
  }

  function handleMouseMove(): void {
    resetHideTimer();
  }

  function handleMouseLeave(): void {
    if (hideTimeout) {
      clearTimeout(hideTimeout);
    }
    if (playerState.isPlaying && !isControlsHovered) {
      showControls = false;
    }
  }

  function handleControlsMouseEnter(): void {
    isControlsHovered = true;
    showControls = true;
    if (hideTimeout) {
      clearTimeout(hideTimeout);
    }
  }

  function handleControlsMouseLeave(): void {
    isControlsHovered = false;
    resetHideTimer();
  }

  // Show controls when video is paused
  $effect(() => {
    if (!playerState.isPlaying) {
      showControls = true;
      if (hideTimeout) {
        clearTimeout(hideTimeout);
      }
    } else {
      resetHideTimer();
    }
  });

  // Cleanup timeout on component unmount
  $effect(() => {
    return () => {
      if (hideTimeout) {
        clearTimeout(hideTimeout);
      }
    };
  });

  function onLoading(loading: boolean): void {
    playerState.isLoading = loading;
  }

  function onError(message: string): void {
    playerState.error = message;
    playerState.isLoading = false;
  }

  function handleLoadStart(): void {
    onLoading(true);
  }

  function handleLoadedData(): void {
    onLoading(false);
    if (playerState.videoElement) {
      playerState.duration = playerState.videoElement.duration;

      if (restoring) {
        console.log("Restoring playback state:", { resumeTime, resumePlaying });
        if (resumeTime > 0) {
          playerState.videoElement.currentTime = resumeTime;
        }

        if (resumePlaying) {
          playerState.videoElement.play().catch((error) => {
            console.error("Auto-play failed:", error);
          });
        } else {
          playerState.videoElement.pause();
          playerState.isPlaying = false;
        }

        restoring = false;
      } else {
        playerState.videoElement.play().catch((error) => {
          console.error("Auto-play failed:", error);
        });
      }
    }
  }

  function handleLoadedMetadata(): void {
    if (playerState.videoElement) {
      playerState.duration = playerState.videoElement.duration;
      const { videoWidth, videoHeight } = playerState.videoElement;
      if (videoWidth && videoHeight) {
        videoAspectRatio = videoWidth / videoHeight;
      }
    }
  }

  function handleTimeUpdate(): void {
    if (playerState.videoElement) {
      playerState.currentTime = playerState.videoElement.currentTime;
    }
  }

  function handleSeeked(): void {
    if (playerState.videoElement) {
      playerState.currentTime = playerState.videoElement.currentTime;
    }
  }

  function handleError(event: Event): void {
    console.error("Video error:", event);

    if ("path" in event && event.path) {
      console.error("Event path:", event.path);
      if (Array.isArray(event.path) && event.path?.[0]) {
        console.error("Event path first element:", event.path[0]);
      }
    }

    const target = event.target as HTMLVideoElement;

    console.group("Video Error Details");
    console.log("Video src:", target.src);
    console.log("Video currentSrc:", target.currentSrc);
    console.log("Video readyState:", target.readyState);
    console.log("Video networkState:", target.networkState);
    console.log("Video error object:", target.error);
    console.groupEnd();

    if (target.error) {
      console.log("Error code:", target.error.code);
      console.log("Error message:", target.error.message);
    }

    let errorMessage = "Unknown video error";

    if (target.error) {
      switch (target.error.code) {
        case MediaError.MEDIA_ERR_ABORTED:
          errorMessage = "Video loading was aborted";
          break;
        case MediaError.MEDIA_ERR_NETWORK:
          errorMessage = "Network error while loading video";
          break;
        case MediaError.MEDIA_ERR_DECODE:
          errorMessage = "Video format not supported or corrupted";
          break;
        case MediaError.MEDIA_ERR_SRC_NOT_SUPPORTED:
          errorMessage = "Video format not supported";
          break;
        default:
          errorMessage = `Video error: ${target.error.message || "Unknown error"}`;
      }
    }

    onError(errorMessage);
    onLoading(false);
  }

  function handleCanPlay(): void {
    // console.log("Video can start playing");
    onLoading(false);
  }

  function handlePlay(): void {
    if (!playerState.videoElement || !playerState.currentVideo) return;

    playerState.isPlaying = true;
  }

  function handlePause(): void {
    playerState.isPlaying = false;
  }

  function handleEnded(): void {
    const currentVideo = playerState.currentVideo;
    if (!currentVideo) return;

    if (queue.repeatMode === "one") {
      // Repeat the current video
      console.log("Repeating current video");
      if (playerState.videoElement) {
        playerState.videoElement.currentTime = 0;
        playerState.currentTime = 0;
        void playerState.videoElement.play();
      }

      return;
    }

    // Always attempt to play next video for repeatMode 'all' and 'off'.
    videoAspectRatio = null;
    playerState.playNextVideo();
  }

  function handleClick(): void {
    const videoContainer = document.querySelector("#video-player") as HTMLElement | null;
    if (videoContainer) {
      videoContainer.focus();
    }
  }

  async function handleDblClick(ev: MouseEvent): Promise<void> {
    const target = ev.target as HTMLElement | null;

    // If there's already a video element mounted, don't treat dblclicks that
    // originate inside the controls as a toggle action.
    if (playerState.videoElement && target && typeof target.closest === "function") {
      const controlsElement = target.closest("#media-controls");
      if (controlsElement) return;
    }

    // If the double-click happened on the video element or its container, toggle play/pause
    // or loading the file system structure.
    if (target && (target.tagName === "VIDEO" || target.closest("#video-player"))) {
      if (!queue.currentItem) await fileBrowserState.loadFileSystemStructure();
      else await playerState.togglePlayPause();
    }
  }
</script>

<div
  class={cn(
    "group relative flex h-full w-full flex-1 flex-col",
    !queue.currentItem &&
      "transition-all duration-300 ease-out hover:bg-slate-100/15 hover:shadow-inner hover:backdrop-blur-md"
  )}
  id="video-player"
>
  {#if queue.currentItem}
    <div
      class={cn(
        "relative flex min-h-0 flex-1 items-center justify-center bg-black transition-all duration-300",
        !showControls && "cursor-none"
      )}
      onclick={handleClick}
      ondblclick={handleDblClick}
      onmousemove={handleMouseMove}
      onmouseleave={handleMouseLeave}
    >
      <div
        class="shrink-0"
        style:max-width={aspectRatio === "contain" ? "100%" : undefined}
        style:max-height={aspectRatio === "contain" ? "100%" : undefined}
        style:aspect-ratio={aspectRatio === "contain"
          ? videoAspectRatio
            ? `${videoAspectRatio}`
            : "16 / 9"
          : undefined}
      >
        <video
          bind:this={playerState.videoElement}
          src={`file://${queue.currentItem.path}`}
          class={cn("h-full w-full bg-black", aspectRatioClass)}
          onloadstart={handleLoadStart}
          onloadeddata={handleLoadedData}
          onloadedmetadata={handleLoadedMetadata}
          ontimeupdate={handleTimeUpdate}
          onseeked={handleSeeked}
          onerror={handleError}
          oncanplay={handleCanPlay}
          onplay={handlePlay}
          onpause={handlePause}
          onended={handleEnded}
          preload="metadata"
          controls={false}
          controlslist="nodownload nofullscreen noremoteplaybook"
          disablepictureinpicture
        >
        </video>
      </div>

      <VideoInfoDisplay visible={showControls} />
      <UpNextNotification />

      <!-- Floating controls overlay -->
      <div
        class={cn(
          "absolute right-0 bottom-0 left-0 z-10 transition-all duration-300 ease-in-out",
          showControls ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-2 opacity-0"
        )}
        onmouseenter={handleControlsMouseEnter}
        onmouseleave={handleControlsMouseLeave}
      >
        <VideoPlayerControls {aspectRatio} onAspectRatioChange={(mode) => (aspectRatio = mode)} />
      </div>
    </div>
  {:else}
    <div
      class="flex flex-1 items-center justify-center"
      onclick={handleClick}
      ondblclick={handleDblClick}
    ></div>

    <div class="pointer-events-none flex-shrink-0 opacity-0">
      <VideoPlayerControls aspectRatio="contain" onAspectRatioChange={() => {}} />
    </div>
  {/if}
</div>
