// src/renderer/src/components/video-player.svelte
<script lang="ts">
  import { playerState } from "@/state.svelte";
  import { cn } from "@/utils/utils";
  import { makeTimeString } from "@/utils/time";
  import MediaControls from "./video-playback/media-controls.svelte";
  import { loadFileSystemStructure } from "@/utils/file-browser.svelte";

  let controlsTimeout: number | null = null;
  let overlayTimeout: number | null = null;
  let showOverlay = $state(false);

  function onLoading(loading: boolean): void {
    playerState.isLoading = loading;
  }

  function onError(message: string): void {
    playerState.error = message;
    playerState.isLoading = false;
  }

  function handleLoadStart(): void {
    console.log("Video load started");
    onLoading(true);
  }

  function handleLoadedData(): void {
    console.log("Video data loaded");
    onLoading(false);
    if (playerState.videoElement) {
      playerState.duration = playerState.videoElement.duration;
      playerState.videoElement.play().catch((error) => {
        console.error("Auto-play failed:", error);
      });
    }
  }

  function handleLoadedMetadata(): void {
    console.log("Video metadata loaded");
    if (playerState.videoElement) {
      playerState.duration = playerState.videoElement.duration;
    }
  }

  function handleTimeUpdate(): void {
    if (playerState.videoElement) {
      playerState.currentTime = playerState.videoElement.currentTime;
    }
  }

  function handleSeeked(): void {
    if (playerState.videoElement) {
      playerState.currentTime = playerState.videoElement.currentTime;
    }
  }

  function handleError(event: Event): void {
    console.error("Video error:", event);
    const target = event.target as HTMLVideoElement;
    let errorMessage = "Unknown video error";

    if (target.error) {
      switch (target.error.code) {
        case MediaError.MEDIA_ERR_ABORTED:
          errorMessage = "Video loading was aborted";
          break;
        case MediaError.MEDIA_ERR_NETWORK:
          errorMessage = "Network error while loading video";
          break;
        case MediaError.MEDIA_ERR_DECODE:
          errorMessage = "Video format not supported or corrupted";
          break;
        case MediaError.MEDIA_ERR_SRC_NOT_SUPPORTED:
          errorMessage = "Video format not supported";
          break;
        default:
          errorMessage = `Video error: ${target.error.message || "Unknown error"}`;
      }
    }

    onError(errorMessage);
    onLoading(false);
  }

  function handleCanPlay(): void {
    // console.log("Video can start playing");
    onLoading(false);
  }

  function handlePlay(): void {
    if (!playerState.videoElement || !playerState.currentVideo) return;

    playerState.isPlaying = true;
  }

  function handlePause(): void {
    playerState.isPlaying = false;
  }

  function handleFullscreenChange(): void {
    // isFullscreen = !!document.fullscreenElement;
  }

  function showControlsTemporarily(): void {
    playerState.showControls = true;
    if (controlsTimeout) {
      clearTimeout(controlsTimeout);
    }
    controlsTimeout = setTimeout(() => {
      if (playerState.isPlaying) {
        playerState.showControls = false;
      }
    }, 3000) as unknown as number;
  }

  function showOverlayTemporarily(): void {
    showOverlay = true;
    if (overlayTimeout) {
      clearTimeout(overlayTimeout);
    }
    overlayTimeout = setTimeout(() => {
      showOverlay = false;
    }, 2000) as unknown as number; // Show for 2 seconds
  }

  function handleMouseMove(): void {
    showControlsTemporarily();
    showOverlayTemporarily();
  }

  function handleClick(): void {
    const videoContainer = document.getElementById("video-player");
    if (videoContainer) {
      videoContainer.focus();
    }
  }

  async function handleDblClick(ev: MouseEvent): Promise<void> {
    const target = ev.target as HTMLElement;

    const controlsElement = target.closest("#media-controls");
    if (controlsElement) {
      return;
    }

    if (target.tagName === "VIDEO" || target.id === "video-player") {
      if (playerState.isPlaying) {
        console.log("Double click while playing...");
      } else {
        await loadFileSystemStructure();
      }
    }
  }

  $effect(() => {
    document.addEventListener("fullscreenchange", handleFullscreenChange);
    return () => {
      document.removeEventListener("fullscreenchange", handleFullscreenChange);
      if (controlsTimeout) {
        clearTimeout(controlsTimeout);
      }
      if (overlayTimeout) {
        clearTimeout(overlayTimeout);
      }
    };
  });

  $effect(() => {
    if (!playerState.isPlaying) {
      playerState.showControls = true;
      if (controlsTimeout) {
        clearTimeout(controlsTimeout);
      }
    }
  });

  $effect(() => {
    if (playerState.videoElement) {
      playerState.videoElement.volume = playerState.isMuted ? 0 : playerState.volume;
      playerState.videoElement.muted = playerState.isMuted;
      playerState.videoElement = playerState.videoElement;
    }
  });
</script>

<div class="flex h-full w-full flex-col bg-black">
  <!-- Video container -->
  <div
    class={cn(
      "group relative flex h-[90%] w-full flex-1 items-center justify-center bg-black",
      !playerState.currentVideo && "cursor-pointer transition-all duration-300 hover:bg-gray-800"
    )}
    onmousemove={handleMouseMove}
    onclick={handleClick}
    ondblclick={handleDblClick}
    id="video-player"
  >
    {#if playerState.currentVideo}
      <video
        bind:this={playerState.videoElement}
        src={playerState.currentVideo}
        class="video-no-controls max-h-full max-w-full object-contain"
        onloadstart={handleLoadStart}
        onloadeddata={handleLoadedData}
        onloadedmetadata={handleLoadedMetadata}
        ontimeupdate={handleTimeUpdate}
        onseeked={handleSeeked}
        onerror={handleError}
        oncanplay={handleCanPlay}
        onplay={handlePlay}
        onpause={handlePause}
        preload="metadata"
        crossorigin="anonymous"
        controls={false}
        controlslist="nodownload nofullscreen noremoteplayback"
        disablepictureinpicture
      >
      </video>

      <!-- Hover overlay -->
      <div
        class="absolute left-4 top-4 rounded-lg bg-black bg-opacity-70 p-3 text-white transition-opacity duration-300"
        class:opacity-100={showOverlay}
        class:opacity-0={!showOverlay}
      >
        <div class="text-sm font-medium">
          {playerState.currentVideo?.split("/").pop() || "Unknown"}
        </div>
        <div class="mt-1 text-xs text-gray-300">
          {makeTimeString(playerState.currentTime)} / {makeTimeString(playerState.duration)}
        </div>
        <div class="mt-1 text-xs text-gray-300">
          {playerState.isPlaying ? "Playing" : "Paused"} • Volume: {Math.round(
            playerState.volume * 100
          )}%{playerState.isMuted ? " (Muted)" : ""}
        </div>
      </div>
    {/if}
  </div>

  <MediaControls />
</div>

// src/renderer/src/components/video-player/VideoPlayer.tsx
import { Loader2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { loadFileSystemStructure } from "@/actions/library";
import {
  bindPlaybackVideoElement,
  playNextVideo,
  togglePlayPause,
} from "@/actions/playback";
import { toFileUrl } from "@/lib/media-path";
import { cn } from "@/lib/utils";
import { usePlayerStore } from "@/stores/player";
import { useCurrentQueueItem, useQueueStore } from "@/stores/queue";
import { UpNextNotification } from "./UpNextNotification";
import { VideoInfoOverlay } from "./VideoInfoOverlay";
import { VideoPlayerControls } from "./VideoPlayerControls";

type HoldDirection = "left" | "right" | null;

export default function VideoPlayer() {
  const aspectRatio = usePlayerStore((state) => state.aspectRatio);
  const duration = usePlayerStore((state) => state.duration);
  const error = usePlayerStore((state) => state.error);
  const isLoading = usePlayerStore((state) => state.isLoading);
  const isPlaying = usePlayerStore((state) => state.isPlaying);
  const setCurrentTime = usePlayerStore((state) => state.setCurrentTime);
  const setDuration = usePlayerStore((state) => state.setDuration);
  const setPlayerState = usePlayerStore((state) => state.setPlayerState);
  const repeatMode = useQueueStore((state) => state.repeatMode);
  const currentItem = useCurrentQueueItem();
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const hideTimerRef = useRef<number | null>(null);
  const holdTimerRef = useRef<number | null>(null);
  const holdIntervalRef = useRef<number | null>(null);
  const [showControls, setShowControls] = useState(false);
  const [isControlsHovered, setIsControlsHovered] = useState(false);
  const [holdDirection, setHoldDirection] = useState<HoldDirection>(null);

  const setVideoElementRef = useCallback((element: HTMLVideoElement | null) => {
    videoRef.current = element;
    bindPlaybackVideoElement(element);
  }, []);

  useEffect(() => {
    setPlayerState({ showControls });
  }, [setPlayerState, showControls]);

  useEffect(() => {
    if (!isPlaying) {
      setShowControls(true);
      if (hideTimerRef.current) {
        window.clearTimeout(hideTimerRef.current);
      }
      return;
    }

    resetHideTimer();
    return () => {
      if (hideTimerRef.current) {
        window.clearTimeout(hideTimerRef.current);
      }
    };
  }, [currentItem?.id, isPlaying]);

  function resetHideTimer(): void {
    if (hideTimerRef.current) {
      window.clearTimeout(hideTimerRef.current);
    }

    setShowControls(true);

    if (!isControlsHovered && isPlaying) {
      hideTimerRef.current = window.setTimeout(() => {
        if (!isControlsHovered) {
          setShowControls(false);
        }
      }, 3000);
    }
  }

  function stopHoldSeeking(): void {
    setHoldDirection(null);
    setPlayerState({ isHolding: false });
    if (holdTimerRef.current) {
      window.clearTimeout(holdTimerRef.current);
      holdTimerRef.current = null;
    }
    if (holdIntervalRef.current) {
      window.clearInterval(holdIntervalRef.current);
      holdIntervalRef.current = null;
    }
  }

  useEffect(() => {
    return () => {
      stopHoldSeeking();
    };
  }, [setPlayerState]);

  function startHoldSeeking(direction: HoldDirection): void {
    if (!videoRef.current || !direction) return;
    setPlayerState({ isHolding: true });
    setHoldDirection(direction);

    holdIntervalRef.current = window.setInterval(() => {
      if (!videoRef.current) {
        stopHoldSeeking();
        return;
      }

      const seekAmount = 0.3;
      const currentDuration = duration;
      if (!Number.isFinite(currentDuration)) return;

      const nextTime =
        direction === "right"
          ? Math.min(videoRef.current.currentTime + seekAmount, currentDuration)
          : Math.max(videoRef.current.currentTime - seekAmount, 0);

      videoRef.current.currentTime = nextTime;
      setCurrentTime(nextTime);
    }, 100);
  }

  if (!currentItem) {
    return (
      <div
        className="group text-muted-foreground flex h-full w-full items-center justify-center bg-black/90 text-center transition hover:bg-black/80"
        onDoubleClick={() => {
          void loadFileSystemStructure();
        }}
      />
    );
  }

  return (
    <div className="relative flex h-full w-full flex-col" id="video-player">
      <div
        className={`relative flex min-h-0 flex-1 items-center justify-center bg-black ${
          showControls ? "" : "cursor-none"
        }`}
        id="video-container"
        onDoubleClick={async (event) => {
          const target = event.target as HTMLElement | null;
          if (target?.closest("#media-controls")) return;
          await togglePlayPause();
        }}
        onMouseDown={(event) => {
          if (event.button !== 0 || !videoRef.current) return;
          const target = event.target as HTMLElement | null;
          if (target && !event.currentTarget.contains(target)) return;
          if (target?.closest("#media-controls")) return;
          const rect = containerRef.current?.getBoundingClientRect();
          if (!rect) return;

          const direction: HoldDirection =
            event.clientX - rect.left < rect.width / 2 ? "left" : "right";
          holdTimerRef.current = window.setTimeout(() => {
            startHoldSeeking(direction);
          }, 300);

          const cleanup = () => {
            stopHoldSeeking();
            window.removeEventListener("mouseup", cleanup);
          };
          window.addEventListener("mouseup", cleanup, { once: true });
        }}
        onMouseLeave={() => {
          if (hideTimerRef.current) {
            window.clearTimeout(hideTimerRef.current);
          }
          if (isPlaying && !isControlsHovered) {
            setShowControls(false);
          }
        }}
        onMouseMove={() => resetHideTimer()}
        ref={containerRef}
      >
        <video
          className={`h-full w-full bg-black ${
            aspectRatio === "cover"
              ? "object-cover"
              : aspectRatio === "fill"
                ? "object-fill"
                : "object-contain"
          }`}
          controls={false}
          disablePictureInPicture
          onCanPlay={() => setPlayerState({ isLoading: false })}
          onEnded={() => {
            if (repeatMode === "one" && videoRef.current) {
              videoRef.current.currentTime = 0;
              setCurrentTime(0);
              void videoRef.current.play();
              return;
            }
            void playNextVideo();
          }}
          onError={() => {
            setPlayerState({
              error: "Video format not supported or file could not be played.",
              isLoading: false,
            });
          }}
          onLoadedData={() => {
            setPlayerState({ isLoading: false });
            if (videoRef.current) {
              setDuration(videoRef.current.duration);
              void videoRef.current.play().catch(() => undefined);
            }
          }}
          onLoadedMetadata={() => {
            if (videoRef.current) {
              setDuration(videoRef.current.duration);
            }
          }}
          onLoadStart={() => setPlayerState({ isLoading: true })}
          onPause={() => setPlayerState({ isPlaying: false })}
          onPlay={() => setPlayerState({ isPlaying: true })}
          onSeeked={() => {
            if (videoRef.current) {
              setCurrentTime(videoRef.current.currentTime);
            }
          }}
          onTimeUpdate={() => {
            if (videoRef.current) {
              setCurrentTime(videoRef.current.currentTime);
            }
          }}
          preload="metadata"
          ref={setVideoElementRef}
          src={toFileUrl(currentItem.path)}
        />

        {isLoading ? (
          <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/40">
            <Loader2 className="h-8 w-8 animate-spin text-white" />
          </div>
        ) : null}

        {error ? (
          <div className="border-destructive/30 bg-destructive/10 text-destructive absolute top-6 left-1/2 z-30 -translate-x-1/2 rounded-lg border px-4 py-2 text-sm">
            {error}
          </div>
        ) : null}

        {holdDirection ? (
          <div
            className={cn(
              "pointer-events-none absolute top-1/2 z-20 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-black/40 text-white backdrop-blur-sm",
              holdDirection === "left" ? "left-8" : "right-8",
            )}
          >
            {holdDirection === "left" ? "←" : "→"}
          </div>
        ) : null}

        {showControls && (
          <>
            <VideoInfoOverlay visible={showControls} />
            <UpNextNotification />
            <VideoPlayerControls
              onControlsMouseEnter={() => {
                setIsControlsHovered(true);
                setShowControls(true);
              }}
              onControlsMouseLeave={() => {
                setIsControlsHovered(false);
                resetHideTimer();
              }}
            />
          </>
        )}
      </div>
    </div>
  );
}
