// src/renderer/src/components/ui/kbd.tsx
import type * as React from "react";
import { cn } from "@/lib/utils";

export function Kbd({ className, ...props }: React.ComponentProps<"kbd">): React.ReactElement {
  return (
    <kbd
      className={cn(
        "pointer-events-none inline-flex h-5 min-w-5 select-none items-center justify-center gap-1 rounded bg-muted px-1 font-medium font-sans text-muted-foreground text-xs [&_svg:not([class*='size-'])]:size-3",
        className,
      )}
      data-slot="kbd"
      {...props}
    />
  );
}

export function KbdGroup({ className, ...props }: React.ComponentProps<"kbd">): React.ReactElement {
  return (
    <kbd
      className={cn("inline-flex items-center gap-1", className)}
      data-slot="kbd-group"
      {...props}
    />
  );
}

// src/renderer/src/components/ui/kbd/kbd.svelte
<!--
	Installed from @ieedan/shadcn-svelte-extras
-->

<script lang="ts" module>
  import { tv, type VariantProps } from "tailwind-variants";
  import type { WithChildren } from "bits-ui";

  const style = tv({
    base: "inline-flex place-items-center justify-center gap-1 rounded-md p-0.5",
    variants: {
      variant: {
        outline: "border-border bg-background text-muted-foreground border",
        secondary: "bg-secondary text-muted-foreground",
        primary: "bg-primary text-primary-foreground"
      },
      size: {
        sm: "min-w-6 gap-1.5 p-0.5 px-1 text-sm",
        default: "min-w-8 gap-1.5 p-1 px-2",
        lg: "min-w-9 gap-2 p-1 px-3 text-lg"
      }
    }
  });

  type Size = VariantProps<typeof style>["size"];
  type Variant = VariantProps<typeof style>["variant"];

  export type KbdPropsWithoutHTML = WithChildren<{
    ref?: HTMLElement | null;
    class?: string;
    size?: Size;
    variant?: Variant;
  }>;

  export type KbdProps = KbdPropsWithoutHTML;
</script>

<script lang="ts">
  import { cn } from "$lib/utils";

  let {
    ref = $bindable(null),
    class: className,
    size = "default",
    variant = "outline",
    children
  }: KbdProps = $props();
</script>

<kbd bind:this={ref} class={cn(style({ size, variant }), className)}>
  {@render children?.()}
</kbd>
